import Link from 'next/link'
import { Plus, Users, FileText, Package, TrendingUp, IndianRupee } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { fetchAPI } from '@/lib/api'

export default async function DashboardPage() {
  let invoices = []
  let kpis = {
    totalRevenue: 0,
    outstandingAmount: 0,
    totalInvoicesCount: 0,
    outstandingInvoicesCount: 0,
    totalCustomers: 0,
    totalItems: 0
  }

  try {
    invoices = await fetchAPI('/invoices?limit=5', { cache: 'no-store' })
    kpis = await fetchAPI('/dashboard/kpis', { cache: 'no-store' })
  } catch (error) {
    console.error('Failed to fetch dashboard data:', error)
  }

  const kpiData = [
    { title: 'Total Revenue', value: `₹ ${Number(kpis.totalRevenue).toLocaleString()}`, description: `${kpis.totalInvoicesCount} total invoices`, icon: IndianRupee, color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
    { title: 'Outstanding', value: `₹ ${Number(kpis.outstandingAmount).toLocaleString()}`, description: `${kpis.outstandingInvoicesCount} invoices pending`, icon: TrendingUp, color: 'text-amber-500', bg: 'bg-amber-500/10' },
    { title: 'Total Customers', value: kpis.totalCustomers.toString(), description: 'Active clients', icon: Users, color: 'text-indigo-500', bg: 'bg-indigo-500/10' },
    { title: 'Inventory Items', value: kpis.totalItems.toString(), description: 'Products in catalog', icon: Package, color: 'text-blue-500', bg: 'bg-blue-500/10' },
  ]

  return (
    <div className="space-y-8">
      {/* Header & Quick Actions */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Dashboard overview</h1>
          <p className="text-slate-500">Welcome back! Here's what's happening with your business today.</p>
        </div>
        <div className="flex gap-2">
          <Link href="/sales/invoices/new">
            <Button className="bg-indigo-600 hover:bg-indigo-700 text-white">
              <Plus className="mr-2 size-4" /> Create Invoice
            </Button>
          </Link>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {kpiData.map((kpi, idx) => (
          <Card key={idx}>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium text-slate-500">{kpi.title}</CardTitle>
              <div className={`p-2 rounded-md ${kpi.bg}`}>
                <kpi.icon className={`size-4 ${kpi.color}`} />
              </div>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{kpi.value}</div>
              <p className="text-xs text-slate-500 mt-1">{kpi.description}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Main Content Area */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Recent Invoices Table (Takes up 2/3 width on large screens) */}
        <Card className="lg:col-span-2">
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle>Recent Invoices</CardTitle>
              <p className="text-sm text-slate-500 mt-1">Latest sales generated by your company.</p>
            </div>
            <Link href="/invoices">
              <Button variant="outline" size="sm">View All</Button>
            </Link>
          </CardHeader>
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              <table className="w-full text-sm text-left border-collapse">
                <thead className="bg-slate-50 dark:bg-slate-800/50 text-slate-500 border-b border-t">
                  <tr>
                    <th className="p-4 font-medium">Invoice #</th>
                    <th className="p-4 font-medium">Customer</th>
                    <th className="p-4 font-medium">Date</th>
                    <th className="p-4 font-medium text-right">Amount</th>
                    <th className="p-4 font-medium text-right">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {invoices.slice(0, 5).map((inv: any) => (
                    <tr key={inv.id} className="hover:bg-slate-50/50 dark:hover:bg-slate-800/20">
                      <td className="p-4 font-medium text-indigo-600 dark:text-indigo-400">{inv.invoiceNumber}</td>
                      <td className="p-4">{inv.customer?.name || 'Unknown'}</td>
                      <td className="p-4 text-slate-500">{new Date(inv.issueDate).toLocaleDateString()}</td>
                      <td className="p-4 text-right font-medium">₹ {Number(inv.grandTotal).toLocaleString()}</td>
                      <td className="p-4 text-right">
                        <span className={`inline-flex items-center px-2 py-1 rounded-md text-xs font-medium ring-1 ring-inset ${
                          inv.status === 'PAID' 
                            ? 'bg-emerald-50 text-emerald-700 ring-emerald-600/20 dark:bg-emerald-500/10 dark:text-emerald-400' 
                            : 'bg-amber-50 text-amber-700 ring-amber-600/20 dark:bg-amber-500/10 dark:text-amber-400'
                        }`}>
                          {inv.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                  {invoices.length === 0 && (
                    <tr>
                      <td colSpan={5} className="p-8 text-center text-slate-500">
                        No recent invoices found.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>

        {/* Quick Links / Status (Takes up 1/3 width) */}
        <Card>
          <CardHeader>
            <CardTitle>Quick Links</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <Link href="/customers/new" className="flex items-center p-3 rounded-lg border hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
              <div className="p-2 bg-indigo-100 text-indigo-600 dark:bg-indigo-900/30 dark:text-indigo-400 rounded-md mr-3">
                <Users className="size-4" />
              </div>
              <div>
                <div className="font-medium">Add Customer</div>
                <div className="text-xs text-slate-500">Create a new client profile</div>
              </div>
            </Link>
            
            <Link href="/items/new" className="flex items-center p-3 rounded-lg border hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
              <div className="p-2 bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400 rounded-md mr-3">
                <Package className="size-4" />
              </div>
              <div>
                <div className="font-medium">Add Item</div>
                <div className="text-xs text-slate-500">Expand your product catalog</div>
              </div>
            </Link>

            <Link href="/settings" className="flex items-center p-3 rounded-lg border hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
              <div className="p-2 bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400 rounded-md mr-3">
                <FileText className="size-4" />
              </div>
              <div>
                <div className="font-medium">Update Settings</div>
                <div className="text-xs text-slate-500">Configure your GSTIN & Logo</div>
              </div>
            </Link>
          </CardContent>
        </Card>

      </div>
    </div>
  )
}
